export type PortalFamily = "GEM" | "GEPNIC" | "CUSTOM" | "INFORMATIONAL";

export interface PortalDefinition {
  key: string;
  name: string;
  shortName: string;
  baseUrl: string;
  family: PortalFamily;
  state?: string;
  enabled: boolean;
  supportsFullScrape: boolean;
  supportsIncrementalScrape: boolean;
  supportsAssistedScrape?: boolean;
  unavailableReason?: string;
}

const customAdapterReason =
  "This portal uses a separate interface. Start an assisted session, solve any CAPTCHA yourself, navigate to the public tender list, then import the visible result pages.";

export const PORTALS: PortalDefinition[] = [
  {
    key: "gem",
    name: "Government e-Marketplace",
    shortName: "GeM",
    baseUrl: "https://bidplus.gem.gov.in/all-bids",
    family: "GEM",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "cppp",
    name: "Central Public Procurement Portal",
    shortName: "CPPP",
    baseUrl: "https://eprocure.gov.in/eprocure/app",
    family: "GEPNIC",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "gepnic",
    name: "NIC GePNIC Platform",
    shortName: "GePNIC",
    baseUrl: "https://gepnic.gov.in",
    family: "INFORMATIONAL",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    unavailableReason:
      "GePNIC is the software platform website, not a tender listing portal. Its participating procurement portals are configured separately.",
  },
  {
    key: "ireps",
    name: "Indian Railways E-Procurement System",
    shortName: "IREPS",
    baseUrl: "https://www.ireps.gov.in",
    family: "CUSTOM",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    supportsAssistedScrape: true,
    unavailableReason: customAdapterReason,
  },
  {
    key: "defproc",
    name: "Defence eProcurement Portal",
    shortName: "Defence",
    baseUrl: "https://defproc.gov.in/nicgep/app",
    family: "GEPNIC",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "coal-india",
    name: "Coal India eProcurement",
    shortName: "Coal India",
    baseUrl: "https://coalindiatenders.nic.in/nicgep/app",
    family: "GEPNIC",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "maharashtra",
    name: "Maharashtra eProcurement",
    shortName: "Maharashtra",
    baseUrl: "https://mahatenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Maharashtra",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "gujarat",
    name: "Gujarat nProcure",
    shortName: "Gujarat nProcure",
    baseUrl: "https://tender.nprocure.com/",
    family: "CUSTOM",
    state: "Gujarat",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    supportsAssistedScrape: true,
    unavailableReason: customAdapterReason,
  },
  {
    key: "karnataka",
    name: "Karnataka Public Procurement Portal",
    shortName: "Karnataka",
    baseUrl: "https://kppp.karnataka.gov.in/#/portal/searchTender/live",
    family: "CUSTOM",
    state: "Karnataka",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    supportsAssistedScrape: true,
    unavailableReason: customAdapterReason,
  },
  {
    key: "tamil-nadu",
    name: "Tamil Nadu eProcurement",
    shortName: "Tamil Nadu",
    baseUrl: "https://tntenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Tamil Nadu",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "telangana",
    name: "Telangana eProcurement",
    shortName: "Telangana",
    baseUrl: "https://tender.telangana.gov.in",
    family: "CUSTOM",
    state: "Telangana",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    supportsAssistedScrape: true,
    unavailableReason: customAdapterReason,
  },
  {
    key: "andhra-pradesh",
    name: "Andhra Pradesh eProcurement",
    shortName: "Andhra Pradesh",
    baseUrl: "https://tender.apeprocurement.gov.in/login.html",
    family: "CUSTOM",
    state: "Andhra Pradesh",
    enabled: false,
    supportsFullScrape: false,
    supportsIncrementalScrape: false,
    supportsAssistedScrape: true,
    unavailableReason: customAdapterReason,
  },
  {
    key: "uttar-pradesh",
    name: "Uttar Pradesh eTender",
    shortName: "Uttar Pradesh",
    baseUrl: "https://etender.up.nic.in/nicgep/app",
    family: "GEPNIC",
    state: "Uttar Pradesh",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "rajasthan",
    name: "Rajasthan eProcurement",
    shortName: "Rajasthan",
    baseUrl: "https://eproc.rajasthan.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Rajasthan",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "madhya-pradesh",
    name: "Madhya Pradesh eTender",
    shortName: "Madhya Pradesh",
    baseUrl: "https://mptenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Madhya Pradesh",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "haryana",
    name: "Haryana eTender",
    shortName: "Haryana",
    baseUrl: "https://etenders.hry.nic.in/nicgep/app",
    family: "GEPNIC",
    state: "Haryana",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "punjab",
    name: "Punjab eProcurement",
    shortName: "Punjab",
    baseUrl: "https://eproc.punjab.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Punjab",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "kerala",
    name: "Kerala eTender",
    shortName: "Kerala",
    baseUrl: "https://etenders.kerala.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Kerala",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "west-bengal",
    name: "West Bengal eTender",
    shortName: "West Bengal",
    baseUrl: "https://wbtenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "West Bengal",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "odisha",
    name: "Odisha eProcurement",
    shortName: "Odisha",
    baseUrl: "https://tendersodisha.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Odisha",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "bihar",
    name: "Bihar eProcurement",
    shortName: "Bihar",
    baseUrl: "https://eproc2.bihar.gov.in/EPSV2Web",
    family: "CUSTOM",
    state: "Bihar",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "jharkhand",
    name: "Jharkhand eTender",
    shortName: "Jharkhand",
    baseUrl: "https://jharkhandtenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Jharkhand",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
  {
    key: "assam",
    name: "Assam eTender",
    shortName: "Assam",
    baseUrl: "https://assamtenders.gov.in/nicgep/app",
    family: "GEPNIC",
    state: "Assam",
    enabled: true,
    supportsFullScrape: true,
    supportsIncrementalScrape: true,
  },
];

export function getPortal(key: string): PortalDefinition | undefined {
  return PORTALS.find((portal) => portal.key === key);
}
